x = "-0.843233764530751513324611729773572725750160827"
y = "0.22381804155806995913989829482160200044199335"
zoom = "1e-25"
iterations = 100_000
width = 800
height = 800
palette = "magma"
ssaa = true
batch_iter = 10000
color_scale = 1.0
color_mode = "iterations"
