x = "-0.12702288604303376058504939571344674642157173"
y = "-0.98728474138900681012772183234313984426625069"
zoom = "1e-24"
iterations = 100_000
width = 400
height = 400
palette = "cividis"
ssaa = true
batch_iter = 10000
color_scale = 4.0
color_mode = "smooth_iterations"
