x = "-0.12702288604303376058504939571344674642157173"
y = "-0.98728474138900681012772183234313984426625069"
zoom = "1e-24"
iterations = 100_000
width = 800
height = 800
palette = "magma"
ssaa = true
batch_iter = 10000
color_scale = 1.0
color_mode = "iterations"
