x = "0.45272105023"
y = "0.396494224267"
zoom = "3e-9"
iterations = 1_000_000
width = 400
height = 400
palette = "cubehelix_default"
ssaa = true
batch_iter = 10000
color_scale = 12.0
color_mode = "iterations"
