x = "-1.15412664822215"
y = "0.30877492767139"
zoom = "7e-11"
iterations = 100_000
width = 400
height = 400
palette = "viridis"
ssaa = true
batch_iter = 10000
color_scale = 6.0
color_mode = "smooth_iterations"
