x = "-1.15412664822215"
y = "0.30877492767139"
zoom = "7e-11"
iterations = 100_000
width = 800
height = 800
palette = "magma"
ssaa = true
batch_iter = 10000
color_scale = 1.0
color_mode = "iterations"
