x = "0.2507465037225357"
y = "-0.000029937331112847903"
zoom = "2e-7"
iterations = 100_000
width = 400
height = 400
palette = "magma"
ssaa = true
batch_iter = 10000
color_scale = 1.0
color_mode = "smooth_wave"
