x = "0.250746364315271"
y = "-0.00002994601778322861"
zoom = "5e-11"
iterations = 100_000
width = 800
height = 800
palette = "magma"
ssaa = true
batch_iter = 10000
color_scale = 1.0
color_mode = "iterations"
